/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CmdRouteImport } from './routes/cmd'
import { Route as ApiStateRouteImport } from './routes/api/state'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiPublicAgentRouteImport } from './routes/api/public/agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmdRoute = CmdRouteImport.update({
  id: '/cmd',
  path: '/cmd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRoute = ApiPublicAgentRouteImport.update({
  id: '/api/public/agent',
  path: '/api/public/agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cmd': typeof CmdRoute
  '/api/state': typeof ApiStateRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/public/agent': typeof ApiPublicAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cmd': typeof CmdRoute
  '/api/state': typeof ApiStateRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/public/agent': typeof ApiPublicAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cmd': typeof CmdRoute
  '/api/state': typeof ApiStateRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/public/agent': typeof ApiPublicAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cmd' | '/api/state' | '/api/stream' | '/api/public/agent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cmd' | '/api/state' | '/api/stream' | '/api/public/agent'
  id:
    | '__root__'
    | '/'
    | '/cmd'
    | '/api/state'
    | '/api/stream'
    | '/api/public/agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CmdRoute: typeof CmdRoute
  ApiStateRoute: typeof ApiStateRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiPublicAgentRoute: typeof ApiPublicAgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cmd': {
      id: '/cmd'
      path: '/cmd'
      fullPath: '/cmd'
      preLoaderRoute: typeof CmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent': {
      id: '/api/public/agent'
      path: '/api/public/agent'
      fullPath: '/api/public/agent'
      preLoaderRoute: typeof ApiPublicAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CmdRoute: CmdRoute,
  ApiStateRoute: ApiStateRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiPublicAgentRoute: ApiPublicAgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
